### ISSUE TITLE
recovery subscibe info when retry to connect the mqtt server

### ISSUE THREAD

**Issue by liqiangno1** [Revalcon/MQTTnet.EventBus#2]
The project is so awesome! but there is a little issue that when the client retry to connect the server . the subscibe info is losted.  Can I recovery them by inject IEventBusSubscriptionsManager to IMqttPersisterConnection? or any other idea?

**Comment by arttonoyan** [comment]
Thanks for your question. 
I am glad you like our project. 
I will look at the problem as soon as possible and response.

**Comment by arttonoyan** [comment]
Could you please describe the case step by step (connect, subscribe disconnect? ). All the subscriptions are collected in the IEventBusSubscriptionsManager and this was [injected ](https://github.com/Revalcon/MQTTnet.EventBus/blob/master/MQTTnet.EventBus/MQTTnet.EventBus/DependencyInjectionExtensions.cs)with singletone.

**Comment by liqiangno1** [comment]
> Could you please describe the case step by step (connect, subscribe disconnect? ). All the subscriptions are collected in the IEventBusSubscriptionsManager and this was [injected ](https://github.com/Revalcon/MQTTnet.EventBus/blob/master/MQTTnet.EventBus/MQTTnet.EventBus/DependencyInjectionExtensions.cs)with singletone.
> You meant when you are disconnected you should resubscribe?
the IEventBusSubscriptionsManager  just record the subscriptions info not really subscriptions
1.  start the project and subscribe the topic
2.  restart the mqtt broker server
3.  then the project will reconnect the mqtt server but the  subscriptions have been lost.

**Comment by arttonoyan** [comment]
Sorry for my late response.
Yes, you are write 
> the subscibe info is losted

It comes from Mosquitto broker.
In the next Release I will add that functionality and you easily can subscribe all topics.
I think I add new function with name `ReSubscribeAllTopics()` or like that.

Thank you for your comment, it is really important functionality which is messy, I will surely add.

**Comment by liqiangno1** [comment]
> Sorry for my late response.
> Yes, you are write
> 
> > the subscibe info is losted
> 
> It comes from Mosquitto broker.
> In the next Release I will add that functionality and you easily can subscribe all topics.
> I think I add new function with name `ReSubscribeAllTopics()` or like that.
> 
> Thank you for your comment, it is really important functionality which is messy, I will surely add.

Ok, Thank you so much!

**Comment by arttonoyan** [comment]
We already have an updated version of app and now you can use "ReSubscribeAllTopicsAsync" function.
If you can, please test the function and if everything is ok I will close the issue.

**Comment by liqiangno1** [comment]
> We already have an updated version of app and now you can use "ReSubscribeAllTopicsAsync" function.
> If you can, please test the function and if everything is ok I will close the issue.
It's so great! But I think it's better to auto recovery the subscribe info when reconnect the mqtt server. What do you think?
